name: Build OpenBLAS

on:
  push:
    branches:
      - master

jobs:
  linux_build:
    name: Building on Linux
    runs-on: ubuntu-latest
    continue-on-error: true
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Clone OpenBLAS
        run: |
          git clone https://github.com/xianyi/OpenBLAS.git
        shell: bash

      - name: Build OpenBLAS
        run: |
          cd OpenBLAS
          make NUM_THREADS=128 DYNAMIC_ARCH=ON DYNAMIC_LIST='CORE2;NEHALEM;SANDYBRIDGE;BULLDOZER;HASWELL'
          make install PREFIX=../openblas_install

      - name: Generated Files
        run: |
          tree openblas_install

      - name: File Search
        run : |
          python file_search.py

      - name: Archive OpenBLAS Build
        uses: actions/upload-artifact@v2
        with:
          name: OpenBLAS_Linux
          path: openblas_install
          retention-days: 3

  mac_build:
    name: Building on Mac OS
    runs-on: macos-latest
    continue-on-error: true
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Get "tree" command
        run: |
          brew install tree

      - name: Clone OpenBLAS
        run: |
          git clone https://github.com/xianyi/OpenBLAS.git
        shell: bash

      - name: Build OpenBLAS
        run: |
          cd OpenBLAS
          make NUM_THREADS=128 DYNAMIC_ARCH=ON DYNAMIC_LIST='CORE2;NEHALEM;SANDYBRIDGE;BULLDOZER;HASWELL'
          make install PREFIX=../openblas_install

      - name: Generated Files
        run: |
          tree openblas_install

      - name: File Search
        run : |
          python file_search.py

      - name: Archive OpenBLAS Build
        uses: actions/upload-artifact@v2
        with:
          name: OpenBLAS_OSX
          path: openblas_install
          retention-days: 3

  windows_build:
    name: Building on Windows
    runs-on: windows-latest
    continue-on-error: true
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - name: Setup WSL
        uses: Vampire/setup-wsl@v1.1.0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v2

      - name: Clone OpenBLAS
        run: |
          git clone https://github.com/xianyi/OpenBLAS.git
        shell: bash

      - name: Install Conda things
        run: |
          conda config --add channels conda-forge --force
          conda config --set auto_update_conda false
          conda install --yes --quiet clangdev cmake ninja flang=11.0.1

      - name: Build OpenBLAS
        run: |
          cd OpenBLAS
          mkdir build
          cd build

          cmake -G "Ninja" -DBUILD_SHARED_LIBS=ON -DCMAKE_C_COMPILER:FILEPATH=cl -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=ninja ..
          cmake --build .

      - name: Generated Files
        run: |
          cd openblas_install
          dir /a-D /S /B
        shell: cmd

      - name: File Search
        run : |
          python file_search.py

      - name: Archive OpenBLAS Build
        uses: actions/upload-artifact@v2
        with:
          name: OpenBLAS_Windows_1
          path: openblas_install

      - name: Archive OpenBLAS Build (FULL)
        uses: actions/upload-artifact@v2
        with:
          name: OpenBLAS_Windows_1_FULL
          path: located_files
          retention-days: 3

  windows_build_2:
    name: Building on Windows (V2)
    runs-on: windows-latest
    continue-on-error: true
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - name: Setup WSL
        uses: Vampire/setup-wsl@v1.1.0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Visual Studio Shell
        uses: egor-tensin/vs-shell@v2

      - name: Clone OpenBLAS
        run: |
          git clone https://github.com/xianyi/OpenBLAS.git
        shell: bash

      - name: Install Things
        run: |
          conda update -n base conda -y
          conda config --add channels conda-forge
          conda install -y cmake flang clangdev perl libflang ninja -y
        shell: pwsh

      # cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DCMAKE_MT=mt -DBUILD_WITHOUT_LAPACK=no -DNOFORTRAN=0 -DNUM_THREADS=128 -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release
      - name: Configure CMake
        run: |
          cd OpenBLAS

          set "LIB=%CONDA_PREFIX%\Library\lib;%LIB%"
          set "CPATH=%CONDA_PREFIX%\Library\include;%CPATH%"
          mkdir build
          cd build
          
          cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DCMAKE_MT=mt -DBUILD_WITHOUT_LAPACK=no -DNOFORTRAN=0 -DNUM_THREADS=128 -DDYNAMIC_ARCH=ON -DDYNAMIC_LIST='CORE2;NEHALEM;SANDYBRIDGE;BULLDOZER;HASWELL' -DCMAKE_BUILD_TYPE=Release
        shell: pwsh

      - name: Build OpenBLAS
        run: |
          cd OpenBLAS
          cd build
          cmake --build . --config Release
        shell: pwsh

      - name: Generated Files
        run: |
          dir /a-D /S /B
        shell: cmd

      - name: File Search
        run : |
          python file_search.py

      - name: Archive OpenBLAS Build
        uses: actions/upload-artifact@v2
        with:
          name: OpenBLAS_Windows_V2
          path: located_files
          retention-days: 3

  windows_build_3:
    name: Building on Windows (V3)
    runs-on: windows-latest
    continue-on-error: true
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - name: Setup WSL
        uses: Vampire/setup-wsl@v1.1.0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v2

      - name: Clone OpenBLAS
        run: |
          git clone https://github.com/xianyi/OpenBLAS.git
        shell: bash

      - name: Install Conda things
        run: |
          conda config --add channels conda-forge --force
          conda config --set auto_update_conda false
          conda install --yes --quiet clangdev cmake ninja flang=11.0.1

      - name: Build OpenBLAS
        run: |
          cd OpenBLAS
          mkdir build
          cd build

          cmake -G "Ninja" -DBUILD_SHARED_LIBS=ON -DCMAKE_C_COMPILER:FILEPATH=cl -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=ninja -DNUM_THREADS=128 -DDYNAMIC_ARCH=ON -DDYNAMIC_LIST='CORE2;NEHALEM;SANDYBRIDGE;BULLDOZER;HASWELL' ..
          cmake --build .

      - name: Generated Files
        run: |
          dir /a-D /S /B
        shell: cmd

      - name: File Search
        run : |
          python file_search.py

      - name: Archive OpenBLAS Build
        uses: actions/upload-artifact@v2
        with:
          name: OpenBLAS_Windows_V3
          path: located_files
          retention-days: 3
