name: Build OpenBLAS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  linux_build:
    name: Building on Linux
    runs-on: ubuntu-latest
    continue-on-error: true
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Clone OpenBLAS
        run: |
          git clone https://github.com/xianyi/OpenBLAS.git
        shell: bash

      - name: Build OpenBLAS
        run: |
          cd OpenBLAS
          make NUM_THREADS=128 DYNAMIC_ARCH=ON DYNAMIC_LIST='CORE2;NEHALEM;SANDYBRIDGE;BULLDOZER;HASWELL'
          make install PREFIX=../openblas_install

      - name: Generated Files
        run: |
          tree openblas_install

  mac_build:
    name: Building on Mac OS
    runs-on: macos-latest
    continue-on-error: true
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Get "tree" command
        run: |
          brew install tree

      - name: Clone OpenBLAS
        run: |
          git clone https://github.com/xianyi/OpenBLAS.git
        shell: bash

      - name: Build OpenBLAS
        run: |
          cd OpenBLAS
          make NUM_THREADS=128 DYNAMIC_ARCH=ON DYNAMIC_LIST='CORE2;NEHALEM;SANDYBRIDGE;BULLDOZER;HASWELL'
          make install PREFIX=../openblas_install

      - name: Generated Files
        run: |
          tree openblas_install

  windows_build:
    name: Building on Windows
    runs-on: windows-latest
    continue-on-error: true
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - name: Setup WSL
        uses: Vampire/setup-wsl@v1.1.0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v2

      - name: Clone OpenBLAS
        run: |
          git clone https://github.com/xianyi/OpenBLAS.git
        shell: bash

      - name: Install Conda things
        run: |
          conda config --add channels conda-forge --force
          conda config --set auto_update_conda false
          conda install --yes --quiet clangdev cmake ninja flang=11.0.1

      - name: Build OpenBLAS
        run: |
          cd OpenBLAS
          mkdir build
          cd build

          cmake -G "MinGW Makefiles" -DNOFORTRAN=1 ..
          cmake -DCMAKE_INSTALL_PREFIX:PATH=../../openblas_install -DNUM_THREADS=128 -DDYNAMIC_ARCH=ON -DDYNAMIC_LIST='CORE2;NEHALEM;SANDYBRIDGE;BULLDOZER;HASWELL' ..
          cmake --build . --target install --config Release

      - name: Generated Files
        run: |
          cd openblas_install
          dir /a-D /S /B
        shell: cmd

  wsl_build:
    name: Building on Windows Subsystem for Linux
    runs-on: windows-latest
    continue-on-error: true
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - name: Setup WSL
        uses: Vampire/setup-wsl@v1.1.0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Visual Studio Shell
        uses: egor-tensin/vs-shell@v2

      - name: Clone OpenBLAS
        run: |
          git clone https://github.com/xianyi/OpenBLAS.git
        shell: bash

      - name: Install Things
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential gcc-mingw-w64-x86-64 gfortran-mingw-w64-x86-64
        shell: wsl-bash {0}

      - name: Build OpenBLAS
        run: |
          cd OpenBLAS
          
          make BINARY=64 USE_THREAD=1 NUM_THREADS=128 DYNAMIC_ARCH=ON DYNAMIC_LIST='CORE2;NEHALEM;SANDYBRIDGE;BULLDOZER;HASWELL' HOSTCC=gcc CC=x86_64-w64-mingw32-gcc FC=x86_64-w64-mingw32-gfortran CFLAGS='-static-libgcc -static-libstdc++ -static -ggdb' FFLAGS='-static' && mv -f libopenblas.dll.a libopenblas.lib

      - name: Generated Files
        run: |
          dir /a-D /S /B
        shell: cmd
